version: '3.8'

services:
  redis-clima:
    build: .
    image: juanbeltran09/redis-clima-iot:latest
    container_name: redis-clima-iot
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
